### PR TITLE
Run satdump with sudo

### PR DESCRIPTION
**Pull request by nxugget**
Without **sudo**, **satdump** show this error : `cannot create directories: Permission denied [/home/[USER]/.config/satdump`
So, no **TLE** can be loaded and the capture generated look like this :
Screenshot 2024-04-24 at 8 42 38 AM

### CODE REVIEW

**Comment by PhilRepisky** [comment]
did you follow the installation instructions?


and that our project can access superuser priviliges for certain things like moving files around in the audio and image directory etc.

To achieve this, run:

`echo "$USER ALL=(ALL) NOPASSWD: /bin/ls" | sudo tee -a /etc/sudoers`

Then reboot the computer:

`sudo reboot`

**Comment by nxugget** [comment]
I'd already follow all of the install instructions. 
This is my **/etc/sudoers** : 
```bash
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "@include" directives:

@includedir /etc/sudoers.d
[USER] ALL=(ALL) NOPASSWD: /bin/ls

**Comment by PhilRepisky** [comment]
can you confirm the ownership + group of `~/.config`?

can you also provide the snippet from the `/var/log/raspberry-noaa-v2/output.log` where this occurs?

**Comment by nxugget** [comment]
Okay, I don't understand why but the **owner** of  `~/.config` was **root** :
`drwxr-xr-x  3 root   root   4096 Apr 23 13:48 .config`
I ran `sudo chown [USER]:[GROUP].config` and I spot this in **satdump** log : 
```
(W) No user configuration found! Keeping defaults.
...
(I) Loading TLEs from /home/[USER]/.config/satdump/satdump_tles.txt
(I) 0 TLEs loaded!
```

Moreover, I see this : 
```bash
> sudo ls -la /root/.config
drwxr-xr-x 2 root root 4096 Apr 25 23:22 satdump
```

**Comment by PhilRepisky** [comment]
can you re-run the `./install_and_upgrade.sh` script? 

then recheck the contents of `satdump_tles.txt`?

if its empty (didn't download new TLEs), then the `./scripts/schedule.sh -x -t' command will fill it in

then check that it runs?

**Comment by nxugget** [comment]
Ok thanks, it's seems to be better cause **TLE** are loaded but I have another issue... Capture does not work, and the problem must come from these errors in the  `output.log` : 
```
rm: cannot remove './dataset.json': No such file or directory
rm: cannot remove './product.cbor': No such file or directory
26-04-2024 20:28 /home/[USER]/raspberry-noaa-v2/scripts/receive_noaa.sh INFO : Files recorded
26-04-2024 20:28 /home/[USER]/raspberry-noaa-v2/scripts/receive_noaa.sh INFO : Resampling down audio
/usr/bin/sox WARN wav: Premature EOF on .wav input file
/usr/bin/sox WARN rate: rate clipped 190330 samples; decrease volume?
/usr/bin/sox WARN dither: dither clipped 166338 samples; decrease volume?
26-04-2024 20:28 /home/[USER]/raspberry-noaa-v2/scripts/receive_noaa.sh INFO : Deleting audio files
26-04-2024 20:28 /home/[USER]/raspberry-noaa-v2/scripts/receive_noaa.sh INFO : No images found - not pushing anywhere
```

**Comment by PhilRepisky** [comment]
this will be a lot harder to diagnose, can we move this to a bug-ticket if the original question is resolved? 

your `settings.yml` and full `output.log` would be needed 

also confirmation that you're able to dial in your antenna reception to 137Mhz. Suggestion would be a manual capture using 'satdump-ui' to confirm a lot about your physical setup

**Comment by nxugget** [comment]
Okay, thanks you very much for your help :)

**Pull request closed without merging**
