### PR TITLE
Succesfully integrated MeteorDemod into GNU Radio section

### PR DESCRIPTION
**Pull request by MihajloPi**
I've successfully integrated MeteorDemod into both RTL_FM and GNU Radio section of the script and Discord and email pushing work!

### CODE REVIEW

**Comment by MihajloPi** [comment]
I've just dried up the code in `receive_meteor.sh` A LOT by reusing common steps for both `rtl_fm` and `gnuradio` if branches.

**Comment by dom-robinson** [comment]
ok so notes from overnight test install to latest bullseye

Install seemed very smooth. 

added email config and rebooted.

This morning had a perfect Noaa pass, but thought i had missed the m2 which was actually before the noaa pass, then the m2 pass popped up a few mins later  - and it was perfect apart from histograms and polar mapping.

Screenshot 2022-01-18 at 08 57 49
.

Screenshot 2022-01-18 at 08 58 44
.


Polar mapping and histogram also failed on Noaa. So i am looking into the logs - probably a simple dependancy...

**Comment by dom-robinson** [comment]
id also think about some compression on the final image files.  They are coming in at 6503 × 6461 and about 13Mb  and will both kill PI storage and take a long time to view on the web UI. Perhaps an 'archive_res' setting? or just a hard coding to downscale them?

**Comment by dom-robinson** [comment]
fixed the polar imaging with a simple ```pip install numpy --upgrade``` at command line

**Comment by dom-robinson** [comment]
I discovered a bunch of images that had been produced (and are really good) but that didn't make it to the display - QUickly patched it by replacing 75 with a copy of line 73

https://github.com/jekhokie/raspberry-noaa-v2/blob/6300083331bbada372084f29c89ff9c59137202a/webpanel/App/Models/Capture.php#L75

**Comment by dom-robinson** [comment]
Screenshot 2022-01-18 at 11 14 44

As mentioned in previous comment

**Comment by dom-robinson** [comment]
Pretty sure that this [ line 30 ](https://github.com/jekhokie/raspberry-noaa-v2/blob/6300083331bbada372084f29c89ff9c59137202a/scripts/image_processors/histogram.sh#L30)

```gmic_temp_1="${input_path}/_${input_filename}_c.${input_fileext}" ```

used to work, but gmic has updated now and seems to automatically insert a '1' in the file names.

so my new line 30 (still pending a test with a real pass) now reads 
```gmic_temp_1="${input_path}/_${input_filename}_c1.${input_fileext}" ```

**Comment by dom-robinson** [comment]
Update from vince on discord is that on bullseye this is a 1 "on buster its a tilde ~"

Needs checking in due course.

**Comment by dom-robinson** [comment]
> I discovered a bunch of images that had been produced (and are really good) but that didn't make it to the display - QUickly patched it by replacing 75 with a copy of line 73
> 
> https://github.com/jekhokie/raspberry-noaa-v2/blob/6300083331bbada372084f29c89ff9c59137202a/webpanel/App/Models/Capture.php#L75

note that this means that it makes no difference night or day to the enhancement list for meteordemod output.

**Comment by dom-robinson** [comment]
Quick summary of Bullseye setup:

 If you want to try to test it (you are very welcome!) go into the raspberry-noaa folder in your home directory and type 
```git checkout meteor-demod-dev-in-progress ```


then run the install_MeteorDemod.sh first then type 
```pip install numpy --upgrade```


then do the install_and_upgrade.sh

After that if you want to fix the histograms you have to change line 30 of scripts/image_processors/histogram.sh to read 

```gmic_temp_1="${input_path}/_${input_filename}_c1.${input_fileext}"```
 (notice the '1' added after the c).

At that point reboot and you should be good to go.

**Pull request merged**
