### PR TITLE
Add Standalone Direction Polar Plot

### LINKED ISSUE #266: Pass Direction Polar Plot (Standalone Image)
This is the starting point for #258 which produces a directional plot of the satellite pass. This can then be enhanced to produce a transparent background and overlaid on the image directly as an option.

matlibplot - would just need to update polar_plot.py for the direction pass generation to specify this (already tested and working):

```
plt.savefig(out_file, transparent=True)
```

This feature is filed as a complete merge/feature to create isolated pass images in case the user doesn't want the overlay but still wants the pass direction plot.

### PR DESCRIPTION
**Pull request by jekhokie**
Add various bits to enable production of a directional polar plot of the satellite pass. This PR captures the "standalone" image being produced and displayed in the webpanel, and sets the groundwork for an overlay option.

### CODE REVIEW

**Comment by jekhokie** [comment]
Leaving as a draft until evening passes come about and are proven to line up with what is expected.

**Comment by colinluthier** [comment]
```
ax.set_yticks(numpy.arange(90, 0, step=-15))
ax.set_yticklabels(numpy.arange(90, 0, step=-15))
ax.set_xticklabels(['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'])
```

This sets cardinal coordinates and puts 90 in the middle of the annotation. It's untested.

**Comment by jekhokie** [comment]
Note to self - the max elevations are wrong when it's an eastern pass. Needs to be fixed.

**Comment by colinluthier** [comment]
Is the set theta direction code the fix for the y axis being 0-90 instead of 90-0?

**Comment by clarkerz** [comment]
I've got this working on a Raspberry PI 2B with no issues at all - it said to mention if you've got it working on a different RPI. Could this be migrated to a i5/amd64 ubuntu system? Thanks for providing this software, really appreciated. :)

**Pull request merged**
