### PR TITLE
Update some syntax and versions for Bullseye compatibility.

### PR DESCRIPTION
**Pull request by colinluthier**

### CODE REVIEW

**Comment by colinluthier** [comment]
@dom-robinson I think this is ready to merge. Can you merge it when you are happy?

**Comment by dom-robinson** [comment]
Before i merge have you checked the install on Buster? Still good?

**Comment by dom-robinson** [comment]
> Before i merge have you checked the install on Buster? Still good?

@colinluthier From what i am seeing on discord the backward compatibility to buster was NOT 100% confirmed here. In fact those who are trying to install on Buster are failing on the php version issue. I hadn't been following this properly on discord and had thought that bullseye was in effect being developed in Vince's prebuild in isolation.  My bad. 

Problem is now that Buster based builders can't reinstall, nor do a new install, and i am not sure that the few bullseye users are getting a complete install either.

I am strongly tempted to revert this PR and restore the master to working on buster, and wait until it is confirmed to both work on bullseye AND be backward compatible to Buster.

ANy input welcome

**Comment by colinluthier** [comment]
I am getting a complete install on Bullseye without changes. It was before the change was made to move from 7.4 to 7.2. 

I have not had time to look at why the 7.4 code fails is Buster. I think we need to upgrade something. I have been telling Buster users to install the previous stable release. 

If you buy a Raspberry Pi today and follow the official build instructions you get Bulls Eye.

**Comment by dom-robinson** [comment]
hmm. we are going to have to get on this nit soon and make it backward compatible ASAP - there has been a steady train of folks who can't install and I don't think 'upgrade your OS' is the right anwser IMHO...

**Comment by colinluthier** [comment]
@dom-robinson I looked into this. When I first tested this I was flagging all php code as php not php2 or php3. It was running php2 on Buster and php3 on Bullseye. I noticed this and changed it all to run php3 without testing. Sorry for the mess. I should have tested more after finding the ambiguity.

**Pull request merged**
