### PR TITLE
Add a push provider to Matrix

### PR DESCRIPTION
**Pull request by Cadair**
This adds the ability to push to [Matrix](matrix.org) rooms, it sends all the images and the summary like the twitter client, although it probably could post the images in the main loop with the other providers, but would need to send the summary at the end.

I hope this looks good, I didn't end up adding it to the main config file as I thought it would be better to follow the other services, but I would be happy to change it.

### CODE REVIEW

**Comment by colinluthier** [comment]
There is one more step missing this line in install and upgrade:

`python3 scripts/tools/validate_yaml.py config/settings.yml config/settings_schema.json`

Will not check for your new parameter.

**Review by dom-robinson — APPROVED** [review]
Looks good to me

**Comment by colinluthier** [comment]
`ENABLE_MATRIX_PUSH={{ enable_matrix_push|lower }}` 

This has to be in the json file as well. @Cadair 

The file:
`raspberry-noaa-v2/config/settings_schema.json`
After this line:
`"enable_discord_push":        { "type": "boolean" },`
add this line:
`"enable_matrix_push":        { "type": "boolean" },`

and in the required section:

`"enable_discord_push",`

**Comment by Cadair** [comment]
@colinluthier Added :smile:

**Review by colinluthier — APPROVED** [review]

**Pull request merged**
