### PR TITLE
Add Slack push feature

### PR DESCRIPTION
**Pull request by MavEtJu**
I don't have Discord nor are the pictures in any shape to public on Twitter. But I do have a Slack client I'm on all day and I am more than happy to see something nice besides work-related things coming by.

image

To configure it, four new fields are added:

enable_slack_push: false
slack_push_url: ''
slack_push_to: ''
slack_link: 'https://XXXX/captures/listImages'

Thank you!

### CODE REVIEW

**Comment by dom-robinson** [comment]
really nice PR : )
@Cadair / @colinluthier this looks text-book perfect to me.  Gets a 'yes' from me. Can either of you double check and merge if you are happy...

**Comment by dom-robinson** [comment]
Ah - @colinluthier pointed out another PR missed this validation (for the install process) - i *think* same is true here

There is one more step missing this line in install and upgrade:

```python3 scripts/tools/validate_yaml.py config/settings.yml config/settings_schema.json```

**Comment by colinluthier** [comment]
@MavEtJu This just needs the new variables added to the required section of settings_schema.json It looks like it fits near the bottom, the format is
```


"enable_email_schedule_push",   
 "enable_discord_push",    
"discord_webhook_url",    
"enable_twitter_push"

```

**Comment by dom-robinson** [comment]
> @MavEtJu This just needs the new variables added to the required section of settings_schema.json It looks like it fits near the bottom, the format is
> 
> ```
> 
> 
> "enable_email_schedule_push",   
>  "enable_discord_push",    
> "discord_webhook_url",    
> "enable_twitter_push"
> ```

I can see these in the PR now so I am going to merge.

**Comment by dom-robinson** [comment]
This needed a little work to blend with the incoming Matrix Push feature, but it was more confirmation than any code issues. 

I have done that and am merging.

**Pull request merged**
