### PR TITLE
Cloning MeteorDemod directly from the Github + added rain overlay variable

### PR DESCRIPTION
**Pull request by MihajloPi**

### CODE REVIEW

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
Wait this is against the wrong branch?

**Review by Cadair — CHANGES_REQUESTED** [review]
Branch?

**Comment by MihajloPi** [comment]
> Wait this is against the wrong branch?

Can you check out my pull request for `meteordemod-staging` branch?

**Comment by Cadair** [comment]
I did, should we close this one?

**Comment by MihajloPi** [comment]
Ah, sorry, I misunderstood you. I'll add a commit to clone MeteorDemod from master.

**Comment by Cadair** [comment]
That's not what I meant, I mean the `meteor-demod-dev-in-progress` isn't the one we are using, so we should close this PR and make a new one against `-staging`?

**Comment by Cadair** [comment]
This is doing a lot of the same things as #509 can you just split out the rain overlay stuff into it's own PR against the `meteordemod-staging` branch please?

**Pull request closed without merging**
